# Не рабочий(пока чтт)
version: '3.9'

services:
  # ASP.NET Core application
  server_app:
    build:
      context: ./server_app
      dockerfile: Dockerfile
    ports:
      - "5183:5183"
    depends_on:
      - redis
      - mongodb
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USER_SECRETS=/root/.microsoft/usersecrets

  # React application
  client_app:
    build:
      context: ./client_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true

  # Redis
  redis:
    image: redis:7.2.5
    ports:
      - "6370:6370"

  # MongoDB
  mongodb:
    image: mongo:8.0.4
    ports:
      - "27010:27010"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # PostgreSQL
  postgres:
    image: postgres:16.6
    ports:
      - "5430:5430"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db

volumes:
  redis_data:
  mongodb_data:
  postgres_data: