<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\server_app.Application\server_app.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
      <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Authorization">
        <HintPath>..\..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\8.0.10\ref\net8.0\Microsoft.AspNetCore.Authorization.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.Http.Abstractions">
        <HintPath>..\..\..\..\..\..\usr\share\dotnet\shared\Microsoft.AspNetCore.App\8.0.10\Microsoft.AspNetCore.Http.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.Mvc.Abstractions">
        <HintPath>..\..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\8.0.8\ref\net8.0\Microsoft.AspNetCore.Mvc.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.Mvc.Core">
        <HintPath>..\..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\8.0.8\ref\net8.0\Microsoft.AspNetCore.Mvc.Core.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions">
        <HintPath>..\..\..\..\.nuget\packages\microsoft.aspnetcore.app.ref\8.0.10\ref\net8.0\Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
